defaults:
  -
    scope:
      path: "/gnulinux4all/"
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: GNU/Linux 4 All
subtitle: Proyecto de Enseñanza de Codigo Abierto

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: "&copy; Elías Nieva Prieto"

# Side Menu Links
menu:
  - text: Proyecto
    link: /
    icon: ""

  - text: Skills & Offers
    link: /skills-and-offers
    icon: ""

  - text: Contacto
    link: /contact
    icon: ""

  - text: My Resume
    link: /resume
    icon: ""

  - text: Blog Posts
    link: /blog
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/EliasNieva
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/EliasNieva
    icon: fab fa-github-square

  - name: telegram
    link: https://t.me/EliasNieva
    icon: fab fa-telegram-square

  - name: twitter
    link: https://www.twitter.com/EliasNieva
    icon: fab fa-twitter

  - name: mastodon
    link: https://mastodon.social/@EliasNieva
    icon: fab fa-mastodon-square


    
